=== entrecode/ec.sdk/test/mocks/schema/model.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "https://entrecode.de/schema/model",
  "type": "object",
  "required": [
    "modelID",
    "title",
    "titleField",
    "hexColor",
    "fields",
    "locales",
    "hasEntries",
    "created",
    "modified",
    "hooks",
    "policies",
    "config"
  ],
  "properties": {
    "modelID": {
      "$ref": "https://entrecode.de/schema/uuidV4"
    },
    "title": {
      "type": "string",
      "pattern": "^[a-zA-Z0-9_\\-]{1,256}$"
    },
    "description": {
      "type": [
        "string",
        "null"
      ]
    },
    "titleField": {
      "type": "string",
      "pattern": "^[a-zA-Z0-9_\\-]{1,256}$"
    },
    "hexColor": {
      "type": "string",
      "pattern": "^#[A-Fa-f0-9]{6}$"
    },
    "hasEntries": {
      "type": "boolean"
    },
    "rights": {
      "type": "object",
      "required": [
        "get",
        "put",
        "postPublic",
        "postPrivate",
        "delete"
      ],
      "properties": {
        "get": {
          "type": "boolean"
        },
        "put": {
          "type": "boolean"
        },
        "postPublic": {
          "type": "boolean"
        },
        "postPrivate": {
          "type": "boolean"
        },
        "delete": {
          "type": "boolean"
        }
      }
    },
    "fields": {
      "$ref": "#/definitions/fields"
    },
    "created": {
      "type": "string",
      "format": "date-time"
    },
    "modified": {
      "type": "string",
      "format": "date-time"
    },
    "locales": {
      "type": "array",
      "items": {
        "$ref": "https://entrecode.de/schema/locale"
      }
    },
    "hooks": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/hook"
      }
    },
    "sync": {
      "$ref": "#/definitions/sync"
    },
    "policies": {
      "type": "array",
      "items": {
        "$ref": "https://entrecode.de/schema/dm-policy"
      }
    },
    "lastSyncs": {
      "type": "array",
      "items": {
        "type": "object"
      }
    },
    "config": {
      "type": "object"
    },
    "_links": {
      "$ref": "https://entrecode.de/schema/hal#_links"
    }
  },
  "definitions": {
    "request": {
      "type": "object",
      "properties": {
        "uri": {
          "type": "string"
        },
        "body": {
          "type": "object"
        },
        "method": {
          "enum": [
            "get",
            "GET",
            "put",
            "PUT",
            "post",
            "POST",
            "delete",
            "DELETE"
          ]
        },
        "headers": {
          "type": "object",
          "additionalProperties": {
            "type": "string"
          }
        },
        "responseMapping": {
          "type": "object",
          "additionalProperties": {
            "$ref": "#/definitions/jsonTransformation"
          }
        },
        "validate": {
          "type": "object",
          "properties": {
            "status": {
              "type": "integer"
            }
          }
        }
      },
      "required": [
        "uri"
      ]
    },
    "createJWT": {
      "type": "object",
      "properties": {
        "variableToSet": {
          "type": "string"
        },
        "algorithm": {
          "enum": [
            "HS256",
            "HS384",
            "HS512",
            "RS256",
            "RS384",
            "RS512"
          ]
        },
        "expiresIn": {
          "type": "string",
          "pattern": "^((?:\\d+)?\\.?\\d+) *(milliseconds?|msecs?|ms|seconds?|secs?|s|minutes?|mins?|m|hours?|hrs?|h|days?|d|years?|yrs?|y)?$"
        },
        "subject": {
          "type": "string"
        },
        "issuer": {
          "type": "string"
        },
        "secret": {
          "type": "string"
        }
      },
      "required": [
        "variableToSet",
        "algorithm"
      ]
    },
    "hook": {
      "type": "object",
      "properties": {
        "hook": {
          "type": "string",
          "pattern": "^before|after|event$"
        },
        "type": {
          "$ref": "#/definitions/hookTypes"
        },
        "methods": {
          "type": "array",
          "items": {
            "type": "string",
            "pattern": "^get|put|post|delete$"
          }
        },
        "description": {
          "type": "string"
        },
        "config": {
          "$ref": "#/definitions/hookConfig"
        },
        "hookID": {
          "$ref": "https://entrecode.de/schema/uuidV4"
        }
      },
      "required": [
        "hook",
        "type",
        "methods",
        "config"
      ]
    },
    "hookTypes": {
      "enum": [
        "web",
        "sync",
        "mail",
        "mailgun"
      ]
    },
    "hookConfig": {
      "anyOf": [
        {
          "$ref": "#/definitions/webHook"
        },
        {
          "$ref": "#/definitions/syncHook"
        },
        {
          "$ref": "#/definitions/mailgunHook"
        }
      ]
    },
    "webHook": {
      "type": "object",
      "properties": {
        "requests": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/request"
          }
        },
        "createJWT": {
          "$ref": "#/definitions/createJWT"
        },
        "responseMapping": {
          "type": "object",
          "additionalProperties": {
            "$ref": "#/definitions/jsonTransformation"
          }
        }
      },
      "required": [
        "requests"
      ]
    },
    "syncHook": {
      "type": "object",
      "properties": {
        "restrictToID": {
          "oneOf": [
            {
              "type": "null"
            },
            {
              "$ref": "#/definitions/jsonTransformation"
            }
          ]
        },
        "models": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      },
      "required": [
        "models"
      ]
    },
    "mailgunHook": {
      "type": "object",
      "additionalProperties": {
        "$ref": "#/definitions/jsonTransformation"
      }
    },
    "sync": {
      "type": [
        "object",
        "null"
      ],
      "properties": {
        "locale": {
          "type": "string"
        },
        "createJWT": {
          "$ref": "#/definitions/createJWT"
        },
        "requests": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/request"
          }
        },
        "itemMapping": {
          "type": "object",
          "additionalProperties": {
            "$ref": "#/definitions/jsonTransformation"
          }
        },
        "entryRelationTargetModelIDs": {
          "type": "object",
          "additionalProperties": {
            "oneOf": [
              {
                "$ref": "#/properties/modelID"
              },
              {
                "$ref": "#/properties/title"
              }
            ]
          }
        },
        "pathToArray": {
          "type": "string"
        },
        "subResource": {
          "type": "object",
          "properties": {
            "parentModelID": {
              "type": "string"
            },
            "parentIDForRequests": {
              "oneOf": [
                {
                  "type": "string"
                },
                {
                  "type": "object",
                  "additionalProperties": {
                    "$ref": "#/definitions/jsonTransformation"
                  }
                }
              ]
            },
            "entryFieldForParentRelation": {
              "type": "string"
            }
          }
        },
        "singleResource": {
          "type": "object",
          "properties": {
            "itemMapping": {
              "type": "object",
              "additionalProperties": {
                "$ref": "#/definitions/jsonTransformation"
              }
            }
          }
        },
        "remoteID": {
          "type": "object",
          "additionalProperties": {
            "$ref": "#/definitions/jsonTransformation"
          }
        }
      },
      "required": [
        "locale",
        "requests",
        "itemMapping",
        "pathToArray",
        "remoteID"
      ]
    },
    "jsonTransformation": {
      "anyOf": [
        {
          "properties": {
            "__jsonmask": {
              "type": "string"
            },
            "__jsonpath": {
              "type": "string"
            },
            "__array": {
              "type": "boolean"
            },
            "__modifier": {
              "enum": [
                "parseInt",
                "parseFloat",
                "uppercase",
                "lowercase",
                "stringify",
                "replace",
                "stringConcat",
                "date",
                "date_add",
                "date_subtract",
                "phone",
                "emptyStringToNull"
              ]
            },
            "__arguments": {
              "type": "array",
              "minItems": 2,
              "maxItems": 4
            },
            "__value": {
              "$ref": "#/definitions/jsonTransformation"
            },
            "__composite": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/jsonTransformation"
              }
            }
          }
        },
        {
          "type": "array",
          "items": {
            "$ref": "#/definitions/jsonTransformation"
          }
        }
      ]
    },
    "fields": {
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "title",
          "type",
          "description",
          "readOnly",
          "required",
          "unique",
          "localizable",
          "mutable",
          "validation",
          "default"
        ],
        "additionalProperties": false,
        "properties": {
          "title": {
            "type": "string",
            "pattern": "^[a-zA-Z0-9_\\-]{1,256}$"
          },
          "description": {
            "type": [
              "string",
              "null"
            ]
          },
          "type": {
            "enum": [
              "text",
              "formattedText",
              "number",
              "decimal",
              "boolean",
              "id",
              "datetime",
              "location",
              "email",
              "url",
              "phone",
              "json",
              "entry",
              "entries",
              "asset",
              "assets",
              "account",
              "role"
            ]
          },
          "readOnly": {
            "type": "boolean"
          },
          "required": {
            "type": "boolean"
          },
          "unique": {
            "type": "boolean"
          },
          "localizable": {
            "type": "boolean"
          },
          "mutable": {
            "type": "boolean"
          },
          "validation": {
            "type": [
              "string",
              "object",
              "null"
            ]
          },
          "default": {}
        }
      }
    }
  }
}

=== entrecode/ec.sdk/test/mocks/model-single.json
{
  "created": "2016-06-30T14:20:55.083Z",
  "description": "a description",
  "hexColor": "#1EAAF1",
  "fields": [
    {
      "title": "_id",
      "type": "id",
      "readOnly": true,
      "required": true,
      "unique": true,
      "localizable": false,
      "mutable": false,
      "description": "Unique identifier for this entry.",
      "validation": null,
      "default": null
    },
    {
      "title": "_created",
      "type": "datetime",
      "readOnly": true,
      "required": true,
      "unique": false,
      "localizable": false,
      "mutable": false,
      "description": "Timestamp of the creation of this entry.",
      "validation": null,
      "default": "1970-01-01T00:00:00.000Z"
    },
    {
      "title": "_modified",
      "type": "datetime",
      "readOnly": true,
      "required": true,
      "unique": false,
      "localizable": false,
      "mutable": false,
      "description": "Timestamp of the last modification of this entry.",
      "validation": null,
      "default": "1970-01-01T00:00:00.000Z"
    },
    {
      "title": "_creator",
      "type": "id",
      "readOnly": true,
      "required": false,
      "unique": false,
      "localizable": false,
      "mutable": false,
      "description": "User that created this entry.",
      "validation": null,
      "default": null
    },
    {
      "type": "email",
      "title": "sender",
      "unique": false,
      "default": null,
      "mutable": true,
      "readOnly": false,
      "required": false,
      "validation": "",
      "description": "",
      "localizable": false
    },
    {
      "type": "email",
      "title": "recipient",
      "unique": false,
      "default": null,
      "mutable": true,
      "readOnly": false,
      "required": false,
      "validation": "",
      "description": "",
      "localizable": false
    },
    {
      "type": "text",
      "title": "subject",
      "unique": false,
      "default": null,
      "mutable": true,
      "readOnly": false,
      "required": false,
      "validation": "",
      "description": "",
      "localizable": false
    },
    {
      "type": "text",
      "title": "content",
      "unique": false,
      "default": null,
      "mutable": true,
      "readOnly": false,
      "required": false,
      "validation": "",
      "description": "",
      "localizable": false
    }
  ],
  "hasEntries": true,
  "locales": [],
  "hooks": [
    {
      "hook": "event",
      "type": "mail",
      "config": {
        "to": "{{data.recipient}}",
        "from": "{{data.sender}}",
        "text": {
          "__jsonpath": "$.data.content"
        },
        "subject": "finally {{data.subject}} "
      },
      "methods": ["post"],
      "description": "mailtest",
      "hookID": "575c341a-648d-43d3-82c6-f9188c6a2095"
    }
  ],
  "sync": null,
  "modelID": "48e4749d-f44f-499f-87c7-1d73583723f3",
  "modified": "2016-07-15T09:15:05.863Z",
  "title": "eventhookmail",
  "titleField": "_id",
  "policies": [],
  "lastSyncs": [],
  "config": {},
  "_links": {
    "self": {
      "profile": "https://entrecode.de/schema/model",
      "href": "https://datamanager.buffalo.entrecode.de/model?modelID=48e4749d-f44f-499f-87c7-1d73583723f3"
    },
    "collection": {
      "profile": "https://entrecode.de/schema/models",
      "href": "https://datamanager.buffalo.entrecode.de/model?dataManagerID=cce541dc-cdd8-4f34-b6e4-20f15d3b8314"
    },
    "ec:datamanager": {
      "profile": "https://entrecode.de/schema/datamanager",
      "href": "https://datamanager.buffalo.entrecode.de/?dataManagerID=cce541dc-cdd8-4f34-b6e4-20f15d3b8314"
    },
    "ec:model/purge": {
      "href": "https://datamanager.buffalo.entrecode.de/model/purge?modelID=48e4749d-f44f-499f-87c7-1d73583723f3"
    },
    "ec:model/entryHistory": {
      "href": "https://dm-history.buffalo.entrecode.de/api/model?dataManagerID=cce541dc-cdd8-4f34-b6e4-20f15d3b8314&modelID=48e4749d-f44f-499f-87c7-1d73583723f3{&_size}",
      "templated": true
    },
    "ec:model/history": {
      "href": "https://dm-history.buffalo.entrecode.de/entries"
    }
  }
}
